/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kop-v1.glb 
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

export function Kop(props) {
  const { nodes, materials } = useGLTF("/models/kop-v1.glb");
  const screensRef = useRef();

  
  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={0.8} // Strength of the bloom
          luminanceThreshold={0.2} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
          emmisiveIntensity={6}
        />
      </EffectComposer>
      <mesh
        geometry={nodes.keyboard_blinn1_0001.geometry}
        material={materials.PaletteMaterial001}
        position={[0.13, 0, 1.101]}
      />
      <mesh

        geometry={nodes.Plane.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.957, 2.386, -1.564]}
        rotation={[1.564, 0.003, -0.405]}
        scale={[0.735, 1.108, 0.33]}
      />
      <mesh
        geometry={nodes.Keyboard.geometry}
        material={materials.PaletteMaterial002}
        position={[1.187, 1.689, -1.557]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.024, 0.011, 0.02]}
      />
      <mesh
        geometry={nodes.RTX_Sticker.geometry}
        material={materials["RTX Sticker"]}
        position={[0.392, 1.695, -1.303]}
        scale={[0.042, 0.042, 0.044]}
      />
      <mesh
        ref={screensRef}
        geometry={nodes.Plane001.geometry}
        material={materials["Material.001"]}
        position={[-0.955, 2.396, -1.558]}
        rotation={[-1.571, -0.004, 0.401]}
        scale={[0.716, 4.42, 0.341]}
      />
    </group>
  );
}

useGLTF.preload("/models/kop-v1.glb");
