/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

export function Laptop(props) {
  const { nodes, materials } = useGLTF("/models/laptop.glb");
  const screensRef = useRef();

  const chairMaterial = new THREE.MeshPhongMaterial({
    color: "#000",
  });
  const tableMaterial = new THREE.MeshPhongMaterial({
    color: "#582f0e",
  });
  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={0.8} // Strength of the bloom
          luminanceThreshold={0.2} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
        />
      </EffectComposer>
      <group position={[0.64, 0, 0.786]}>
        <mesh
          geometry={nodes.chair_body_blinn1_0.geometry}
          material={chairMaterial}
        />
        <mesh
          geometry={nodes.lamp_bl_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.lamp_white_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.miuse_blinn1_0.geometry}
          material={materials.blinn1}
          position={[-1.42, 0, 0.29]}
        />
        <mesh
          geometry={nodes.pillows_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.stylus_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.table_blinn1_0.geometry}
          material={tableMaterial}
        />
      </group>
      <mesh
        geometry={nodes.keyboard_blinn1_0001.geometry}
        material={materials["blinn1.001"]}
        position={[0.13, 0, 1.101]}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0001.geometry}
        material={materials["blinn1.001"]}
        position={[-0.099, 0, 0.786]}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0001.geometry}
        material={materials["blinn1.001"]}
        position={[0.102, 0, 1.101]}
      />
      <mesh
        ref={screensRef}
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[-0.949, 2.386, -1.544]}
        rotation={[1.564, 0.003, -0.407]}
        scale={[0.747, 1.112, 0.363]}
      />
      <group position={[0.78, 1.675, -1.601]} scale={[0.569, 0.336, 0.347]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Body} />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Matte Black"]}
        />
        <mesh
          geometry={nodes.hdmi.geometry}
          material={materials.Keycaps}
          position={[-0.952, 0.027, -0.391]}
          scale={[0.085, 0.015, 0.071]}
        >
          <group position={[0.006, 0.3, -0.021]} scale={[0.044, 0.216, 0.714]}>
            <mesh geometry={nodes.Cube004.geometry} material={materials.Gold} />
            <mesh
              geometry={nodes.Cube004_1.geometry}
              material={materials.Keycaps}
            />
          </group>
        </mesh>
        <group
          position={[0.952, 0.028, -0.07]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[-0.019, -0.025, -0.019]}
        >
          <mesh
            geometry={nodes.Cylinder003.geometry}
            material={materials.Keycaps}
          />
          <mesh
            geometry={nodes.Cylinder003_1.geometry}
            material={materials.Gold}
          />
        </group>
        <group
          position={[0.715, 0.04, 0.127]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.042, 0.033, 0.059]}
        >
          <mesh
            geometry={nodes.Plane012.geometry}
            material={materials.Keycaps}
          />
          <mesh
            geometry={nodes.Plane012_1.geometry}
            material={materials.Glow}
          />
        </group>
        <group
          position={[-0.953, 0.03, -0.758]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.014, 0.025, 0.014]}
        >
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={materials.Keycaps}
          />
          <mesh
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Body}
          />
        </group>
        <mesh
          geometry={nodes.RTX_Sticker.geometry}
          material={materials["RTX Sticker"]}
          position={[-0.682, 0.058, 0.858]}
          scale={[0.075, 0.126, 0.126]}
        />
        <mesh
          geometry={nodes.Ryzen_Sticker.geometry}
          material={materials["Ryzen Sticker"]}
          position={[-0.86, 0.058, 0.86]}
          scale={[0.076, 0.128, 0.128]}
        />
        <mesh
          geometry={nodes.Screen.geometry}
          material={materials["Matte Black"]}
          position={[-0.003, 0.077, -0.94]}
          rotation={[-1.625, 0, 0]}
        >
          <mesh
            geometry={nodes["Acer-Logo_2011001"].geometry}
            material={materials["Acer-Logo_2011"]}
            position={[0, 0.11, 0.932]}
            rotation={[-3.141, 0, Math.PI]}
            scale={[0.152, 0.257, 0.51]}
          />
          <group
            position={[0.003, 0.035, -0.017]}
            rotation={[1.575, 0, 0]}
            scale={[0.994, 1, 1]}
          >
            <mesh
              geometry={nodes.Plane006.geometry}
              material={materials.Keycaps}
            />
            <mesh
              geometry={nodes.Plane006_1.geometry}
              material={materials.Body}
            />
          </group>
        </mesh>
        <group position={[-0.938, 0.03, -0.585]} scale={[0.589, 0.199, 0.996]}>
          <mesh geometry={nodes.Cube001.geometry} material={materials.Body} />
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={materials.Keycaps}
          />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.Gold} />
        </group>
        <group
          position={[0.938, 0.03, -0.665]}
          rotation={[0, 0, Math.PI]}
          scale={[0.589, 0.199, 0.996]}
        >
          <mesh geometry={nodes.Cube008.geometry} material={materials.Body} />
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials.Keycaps}
          />
          <mesh geometry={nodes.Cube008_2.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Cube008_3.geometry} material={materials.Blue} />
        </group>
        <mesh
          geometry={nodes.USB_Metal.geometry}
          material={materials.Keycaps}
          position={[-0.944, 0.03, -0.166]}
          scale={[0.033, 0.021, 0.065]}
        >
          <group
            position={[0.233, 0.204, 0.006]}
            scale={[-1.052, -0.286, -0.812]}
          >
            <mesh geometry={nodes.Cube012.geometry} material={materials.Blue} />
            <mesh
              geometry={nodes.Cube012_1.geometry}
              material={materials.Gold}
            />
          </group>
        </mesh>
        <mesh
          geometry={nodes.USB_Metal_2.geometry}
          material={materials.Keycaps}
          position={[0.943, 0.03, -0.216]}
          rotation={[0, 0, Math.PI]}
          scale={[0.033, 0.021, 0.065]}
        >
          <group
            position={[0.233, -0.227, 0.006]}
            rotation={[Math.PI, 0, 0]}
            scale={[-1.052, -0.286, -0.812]}
          >
            <mesh geometry={nodes.Cube014.geometry} material={materials.Blue} />
            <mesh
              geometry={nodes.Cube014_1.geometry}
              material={materials.Gold}
            />
          </group>
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/laptop.glb");
